using DataCrafter.Entities;
using Spectre.Console;

namespace DataCrafter.Services.FileIO;

/// <summary>
///     Represents a service for streaming data generated by a Faker instance to a CSV file.
/// </summary>
internal interface IDataFrameCsvSink
{
    /// <summary>
    ///     Streams data generated by a Faker instance to a CSV file.
    /// </summary>
    /// <param name="dataFrameColumns">
    ///     The collection of data frame columns providing information about the data structure.
    /// </param>
    /// <param name="numberOfRows"> The number of rows to generate and stream. </param>
    /// <param name="outputPath"> The path to the CSV file where data will be streamed. </param>
    /// <param name="progressTask"> The progress tracker to update during streaming. </param>
    Task<List<DynamicClass>> StreamToCsv(IList<IDataFrameColumn> dataFrameColumns, int numberOfRows, string outputPath, ProgressTask progressTask);
}
